"""Write FINDINGS.md from the results files.

    python -m tools.findings

The README is the argument; this is the five-line version for someone deciding
whether to open the code. Both are generated, for the same reason: a figure
typed once into prose is a figure that goes stale two commits later and fails
nothing.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "FINDINGS.md"


def _wrap(text: str) -> str:
    """Reflow paragraphs to 92 columns, leaving tables and quotes alone."""
    out = []
    for block in text.split("\n\n"):
        stripped = block.strip("\n")
        # "**bold**" starts a paragraph, not a list, so only real list
        # markers ("- ", "* ") and table/heading/quote lines are left alone.
        is_literal = (stripped.startswith(("#", "|", ">"))
                      or stripped.startswith(("- ", "* "))
                      or "\n|" in stripped)
        if is_literal:
            out.append(stripped)
        else:
            # break_on_hyphens would split "hand-labelled" across lines.
            out.append(textwrap.fill(" ".join(stripped.split()), width=92,
                                     break_on_hyphens=False))
    return "\n\n".join(out) + "\n"


def build() -> str:
    a = json.loads((ROOT / "results" / "analysis.json").read_text())
    v = json.loads((ROOT / "results" / "remedy_validation.json").read_text())
    r = json.loads((ROOT / "results" / "uphold_rates.json").read_text())

    c, g, co = a["composition"], a["grounds"], a["cost"]
    p, ab = a["prediction"], a["investigator_ablation"]
    d = r["by_phrase"]["declined the claim"]
    lo, hi = v["pooled"]["claim_decision_stood_ci95"]
    gs = p["grouped_by_respondent"]["scores"]
    wo = ab["without_investigator_view"]["scores"]
    w = ab["with_investigator_view"]["scores"]
    mc = p["grouped_by_respondent"]["mcnemar"]["majority_vs_tfidf_lr"]
    clean = v["rule_on_clean_sample"]
    delta = 100 * (w["tfidf_lr"]["balanced_accuracy"]
                   - wo["tfidf_lr"]["balanced_accuracy"])

    return _wrap(f"""# Findings

Five, in the order they matter. Every figure here is regenerated by `python -m bench.run`,
`python -m bench.rates` and `python -m tools.findings`; none is typed by hand. The corpus is
{c['decisions_harvested']:,} published Financial Ombudsman decisions, {c['date_min']} to
{c['date_max']}, across {c['distinct_respondents']} respondent firms, of which
{c['benchmark_cases']:,} are about a claim decision.

## F1 — When a declined claim reaches a final decision, the insurer loses about four times in ten

{d['upheld']:,} of {d['total']:,} published decisions mentioning a declined claim were upheld:
**{d['rate']:.1%}** (95% CI {d['ci95'][0]:.1%}–{d['ci95'][1]:.1%}). That comes from the search's
own result totals — two requests, with none of our sampling in it.

It is a rate over *published decisions*, which are the tail of complaints that reached an
ombudsman at all. It is not a claims error rate, and nothing here estimates one.

## F2 — Roughly three in ten of those losses never touch the claim decision

**{v['pooled']['claim_decision_stood_share']:.1%}** of upheld claim complaints leave the claim
outcome intact (95% CI {lo:.1%}–{hi:.1%}, from {v['pooled']['n']} decisions read by hand). The
declinature stood. The insurer lost on delay, on evidence it never asked for, on an explanation
the customer could not follow.

The rule that reproduces this across the whole corpus puts it at
{g['claim_decision_stood_share']:.1%}, inside the hand-labelled interval. Measured on a sample
drawn and labelled *after* the rule was frozen: accuracy {clean['accuracy']:.0%}, precision
{clean['precision']:.1%}, recall {clean['recall']:.1%}.

**An earlier version of that rule said half.** It counted "accept the claim and repair the
laptop" and "increase the cash settlement to £355" as the claim being left alone. That is why
140 decisions were read by hand rather than left to a regex.

## F3 — The complaint costs more than the compensation does

Median compensation, where any is awarded, is **£{co['median_award_gbp']:,.0f}**
({co['cases_with_award']:,} of {g['upheld_cases']:,} upheld decisions,
{co['share_of_upheld_with_award']:.0%}). The ombudsman's case fee is **£680**, and its own
wording is the part worth quoting: *"Respondent financial businesses pay a case fee regardless
of the outcome of a complaint."*

The fee for the complaint existing is more than three times the median award for losing it. The
claim itself, 8% interest, handling time and the client conversation sit on top; only the fee
and the award are measured here.

## F4 — The overturned decisions are identifiable before they are sent

On the facts alone, under a split where no insurer appears on both sides:

| | balanced accuracy | recall on upheld |
|---|---:|---:|
| majority predictor | {gs['majority']['balanced_accuracy']:.3f} | {gs['majority']['recall_upheld']:.3f} |
| TF-IDF + logistic regression | {gs['tfidf_lr']['balanced_accuracy']:.3f} | {gs['tfidf_lr']['recall_upheld']:.3f} |
| nearest published precedents | {gs['precedent_knn']['balanced_accuracy']:.3f} | {gs['precedent_knn']['recall_upheld']:.3f} |

Paired McNemar against the majority predictor: p = {mc['p']:.2g}.

Grouped and random splits agree to within 0.1 points, so this is not the model recognising the
insurer. Nor is it a product on its own: the triage curve in §4 of the README is the honest
version, and it says a system like this earns its place by escalating rather than by deciding.

## F5 — Showing a model the prior adjudicator's opinion is worth {delta:.0f} points

{ab['cases']:,} of the cases carry the first-stage adjudicator's provisional view. With it
removed the linear model scores {wo['tfidf_lr']['balanced_accuracy']:.3f}; with it restored,
{w['tfidf_lr']['balanced_accuracy']:.3f}.

That is the finding worth taking somewhere else. **Any evaluation of a claims model run over
files that already contain a human's opinion is overstating it by roughly this much**, and a
production file at the moment of decision does not contain one.

Making it measurable took three separate leak fixes: the adjudicator's recommendation surviving
a line-based stripper, plural "our Investigators" never matching, and decisions restating a
provisional decision's own intended outcome. Before those, the headline model scored 0.746
rather than {gs['tfidf_lr']['balanced_accuracy']:.3f} — and nothing failed.
""")


def main() -> int:
    OUT.write_text(build())
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
